name: Swift Package

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-name: cwl-demangle-linux-x86_64
          - os: macos-latest
            artifact-name: cwl-demangle-macos-arm64
      fail-fast: false

    name: Build and test package
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Test command line tool
      run: |
        actual=$(.build/debug/cwl-demangle single "_TFC3foo3bar3bazfT_S0_")
        expected="foo.bar.baz() -> foo.bar"
        if [[ "$actual" != *$expected* ]]; then
          echo "Demangle _TFC3foo3bar3bazfT_S0_ expected $expected was $actual"
          exit 1
        fi
    - name: Build release
      run: make build
      if: github.ref_type == 'tag'
    - name: Prepare binary for upload
      run: cp .build/release/cwl-demangle ${{ matrix.artifact-name }}
      if: github.ref_type == 'tag'
    - name: Release
      uses: softprops/action-gh-release@v2.2.1
      if: github.ref_type == 'tag'
      with:
        files: |
          ${{ matrix.artifact-name }}
