name: Swift Package

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-name: cwl-demangle-linux-x86_64
          - os: macos-latest
            artifact-name: cwl-demangle-macos-arm64
      fail-fast: false

    name: Build and test package
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0.3"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Build release
      run: make build
      if: github.ref_type == 'tag'
    - name: Prepare binary for upload
      run: cp .build/release/cwl-demangle ${{ matrix.artifact-name }}
      if: github.ref_type == 'tag'
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          ${{ matrix.artifact-name }}
